from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from hashlib import sha256

from .catalogue import (
    Catalogue,
    CatalogueSourceAdapter,
    PriceResolver,
    StaticCatalogueSourceAdapter,
    build_catalogue_from_source,
)
from .errors import CatalogueValidationError
from .models import CatalogSource, PresentationSource
from .presentation import (
    PresentationSourceAdapter,
    PresentedCatalogue,
    StaticPresentationSourceAdapter,
    build_presented_catalogue,
)


@dataclass(frozen=True)
class CompiledCatalogueBundle:
    """Immutable deployment input compiled from the reviewed catalogue sidecars."""

    bundle_version: str
    expected_presentation_version: str
    catalogue_sources: tuple[CatalogSource, ...]
    fulfilment_expansions: Mapping[str, tuple[str, ...]]
    presentation_sources: tuple[PresentationSource, ...]

    @property
    def catalogue_source_adapter(self) -> CatalogueSourceAdapter:
        return StaticCatalogueSourceAdapter(self.catalogue_sources)

    @property
    def presentation_source_adapter(self) -> PresentationSourceAdapter:
        return StaticPresentationSourceAdapter(self.presentation_sources)


async def compile_catalogue_bundle(
    catalogue_source: CatalogueSourceAdapter,
    price_resolver: PriceResolver,
    fulfilment_expansions: Mapping[str, tuple[str, ...]],
    presentation_source: PresentationSourceAdapter,
) -> CompiledCatalogueBundle:
    """Builds a deployment bundle only after all source and presentation validations pass."""

    catalogue_sources = await catalogue_source.load()
    presentation_sources = await presentation_source.load()
    catalogue = await build_catalogue_from_source(
        StaticCatalogueSourceAdapter(catalogue_sources), price_resolver, fulfilment_expansions
    )
    presented = build_presented_catalogue(catalogue, presentation_sources)
    return CompiledCatalogueBundle(
        bundle_version=_bundle_version(catalogue_sources, fulfilment_expansions, presentation_sources),
        expected_presentation_version=presented.presentation_version,
        catalogue_sources=catalogue_sources,
        fulfilment_expansions={key: tuple(value) for key, value in sorted(fulfilment_expansions.items())},
        presentation_sources=presentation_sources,
    )


async def build_runtime_catalogue(bundle: CompiledCatalogueBundle, price_resolver: PriceResolver) -> Catalogue:
    """Rebuilds the private checkout catalogue from the compiled source inputs."""

    catalogue = await build_catalogue_from_source(
        bundle.catalogue_source_adapter, price_resolver, bundle.fulfilment_expansions
    )
    return catalogue


async def build_runtime_presented_catalogue(
    bundle: CompiledCatalogueBundle, price_resolver: PriceResolver
) -> PresentedCatalogue:
    """Rebuilds the public catalogue and rejects presentation drift from the compiled snapshot."""

    catalogue = await build_runtime_catalogue(bundle, price_resolver)
    presented = build_presented_catalogue(catalogue, await bundle.presentation_source_adapter.load())
    if presented.presentation_version != bundle.expected_presentation_version:
        raise CatalogueValidationError("compiled presentation does not match bundled sources")
    return presented


def render_compiled_catalogue_module(bundle: CompiledCatalogueBundle) -> str:
    """Serializes a bundle into the deterministic private Worker module committed for deployment."""

    payload = {
        "catalogue_sources": [source.__dict__ for source in bundle.catalogue_sources],
        "bundle_version": bundle.bundle_version,
        "expected_presentation_version": bundle.expected_presentation_version,
        "fulfilment_expansions": {key: list(value) for key, value in bundle.fulfilment_expansions.items()},
        "presentation_sources": [source.__dict__ for source in bundle.presentation_sources],
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return f"""# ruff: noqa: E501
\"\"\"Generated by scripts/compile_catalogue.py; do not edit by hand.\"\"\"

from __future__ import annotations

import json

from .catalogue_bundle import CompiledCatalogueBundle
from .models import CatalogSource, PresentationSource

_PAYLOAD = json.loads(
    {encoded!r}
)

COMPILED_CATALOGUE = CompiledCatalogueBundle(
    bundle_version=_PAYLOAD["bundle_version"],
    expected_presentation_version=_PAYLOAD["expected_presentation_version"],
    catalogue_sources=tuple(CatalogSource(**source) for source in _PAYLOAD["catalogue_sources"]),
    fulfilment_expansions={{key: tuple(value) for key, value in _PAYLOAD["fulfilment_expansions"].items()}},
    presentation_sources=tuple(PresentationSource(**source) for source in _PAYLOAD["presentation_sources"]),
)
"""


def _bundle_version(
    catalogue_sources: tuple[CatalogSource, ...],
    fulfilment_expansions: Mapping[str, tuple[str, ...]],
    presentation_sources: tuple[PresentationSource, ...],
) -> str:
    payload = {
        "catalogue_sources": [source.__dict__ for source in catalogue_sources],
        "fulfilment_expansions": {key: list(value) for key, value in sorted(fulfilment_expansions.items())},
        "presentation_sources": [source.__dict__ for source in presentation_sources],
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return "sha256:" + sha256(encoded.encode("utf-8")).hexdigest()
