# ruff: noqa: E501
"""Generated by scripts/compile_catalogue.py; do not edit by hand."""

from __future__ import annotations

import json

from .catalogue_bundle import CompiledCatalogueBundle
from .models import CatalogSource, PresentationSource

_PAYLOAD = json.loads(
    '{"bundle_version":"sha256:e81d6918e30fcfe6be868eb902abd54280588600fde81c045474444c44c35457","catalogue_sources":[{"active":true,"fulfilment_type":"download","fulfilment_version":"test-template-v1","max_quantity":1,"product_key":"TEST-TEMPLATE","stripe_lookup_key":"cr_test_template","title":"Test Digital Template"},{"active":true,"fulfilment_type":"bundle","fulfilment_version":"test-bundle-v1","max_quantity":1,"product_key":"TEST-BUNDLE","stripe_lookup_key":"cr_test_bundle","title":"Test Resource Bundle"},{"active":true,"fulfilment_type":"download","fulfilment_version":"test-free-v1","max_quantity":1,"product_key":"TEST-FREE","stripe_lookup_key":"cr_test_free","title":"Test Free Resource"},{"active":true,"fulfilment_type":"service","fulfilment_version":"test-support-hours-v1","max_quantity":5,"product_key":"TEST-SUPPORT-HOURS","stripe_lookup_key":"cr_test_support_hours","title":"Test Support Hours"}],"expected_presentation_version":"sha256:f9df98a40ac1a83944e74489edab771262e43836723b74524ea964d1c96fbd8b","fulfilment_expansions":{"test-bundle-v1":["TEST-RESOURCE-A","TEST-RESOURCE-B"],"test-free-v1":["TEST-RESOURCE-FREE"],"test-support-hours-v1":["TEST-RESOURCE-SUPPORT-HOURS"],"test-template-v1":["TEST-RESOURCE-TEMPLATE"]},"presentation_sources":[{"image_key":"test-template-cover-v1","product_key":"TEST-TEMPLATE","short_description":"A synthetic downloadable template for storefront testing."},{"image_key":"test-bundle-cover-v1","product_key":"TEST-BUNDLE","short_description":"A synthetic bundle that represents multiple downloadable resources."},{"image_key":"test-free-cover-v1","product_key":"TEST-FREE","short_description":"A synthetic no-cost resource for native free Checkout testing."},{"image_key":"test-support-hours-cover-v1","product_key":"TEST-SUPPORT-HOURS","short_description":"A synthetic service product with a quantity limit of five hours."}]}'
)

COMPILED_CATALOGUE = CompiledCatalogueBundle(
    bundle_version=_PAYLOAD["bundle_version"],
    expected_presentation_version=_PAYLOAD["expected_presentation_version"],
    catalogue_sources=tuple(CatalogSource(**source) for source in _PAYLOAD["catalogue_sources"]),
    fulfilment_expansions={key: tuple(value) for key, value in _PAYLOAD["fulfilment_expansions"].items()},
    presentation_sources=tuple(PresentationSource(**source) for source in _PAYLOAD["presentation_sources"]),
)
